export const actionsEnum = {
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
    LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
    LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
    UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
};
